### ISSUE TITLE
Monoid Implementation Question

### ISSUE THREAD

**Issue by mwalkerwells** [gcanti/flow-static-land#24]
This may be a n00b question, but what is the reason **get**Semigroup, **get**Monoid, ***get***Setoid are implemented differently than map / Functor?

**Monoid:**
```javascript
export function getSemigroup<A>(semigroup: Semigroup<A>): Semigroup<Maybe<A>> {
  return {
    concat(fx, fy) {
      const x = prj(fx)
      const y = prj(fy)
      if (x == null) {
        return fy
      }
      if (y == null) {
        return fx
      }
      return of(semigroup.concat(x, y))
    }
  }
}
```

**Map / Functor**
```javascript
export function map<A, B>(f: (a: A) => B, fa: Maybe<A>): Maybe<B> {
  const a = prj(fa)
  return a == null ? Nothing : inj(f(a))
}
```

It seemed weird that we're not type checking for Monoid...making me wonder how to implement it differently or better understand why it's not possible.

**Type Checks:**
```javascript
if (false) { // eslint-disable-line
  ({
    map,
    ap,
    of,
    chain,
    reduce,
    alt,
    pempty,
    extend
  }: Monad<IsMaybe> &
     Foldable<IsMaybe> &
     Alt<IsMaybe> &
     Plus<IsMaybe> &
     Alternative<IsMaybe> &
     Extend<IsMaybe>)
}
```

**Comment by gcanti** [comment]
`Maybe<A>` is a semigroup *if* `A` is a semigroup, so you need to pass in a type class instance for `A`

```js
function getSemigroup<A>(semigroup: Semigroup<A>): Semigroup<Maybe<A>>
//                           ^
//                           +--- type class instance for `A` 
```

the signature (and the implementation) is almost a word by word translation of the corrsponding PureScript definition (cfr [purescript-maybe](https://github.com/purescript/purescript-maybe))

```purescript
instance semigroupMaybe :: Semigroup a => Semigroup (Maybe a) where
  append Nothing y = y
  append x Nothing = x
  append (Just x) (Just y) = Just (x <> y)
```

Note the `"Semigroup a =>"` type constraint.

> It seemed weird that we're not type checking for Monoid
 
Actually we *are* type checking: `getSemigroup` returns a `Semigroup<Maybe<A>>`

**Comment by mwalkerwells** [comment]
Eh, reading this, now it seems so obvious:
> Maybe<A> is a semigroup if A is a semigroup

Thanks for the clarification!
