### ISSUE TITLE
PR: Adding Documentation for eslint-plugin-flowtype-errors

### ISSUE THREAD

**Issue by amilajack** [gcanti/flow-static-land#29]
This plugin reports flow errors as ESLint errors, which useful for literally everyone who doesn't use nuclide.

Demo:
![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

Would a PR for updating the documentation, regarding this plugin, be welcome?

**Comment by gcanti** [comment]
Nice.

However I don't see how a eslint plugin is related to this library
